package rest.model;

public class Restaurants {
    protected int restaurantId;
    protected String name;
    protected String description;
    protected String menu;
    protected String  hours;
    protected boolean isActive;
    protected String street1 ;
    protected String street2 ;
    protected String city ;
    protected String state ;
    protected String zip ;
    protected CuisineType cuisineType;
    protected Companies company ;

    public enum CuisineType {
		african, american, asian, european, hispanic
	}

    // reading records from MySQL, where we have all fields
    public Restaurants (int restaurantId, String name, String description,
						String menu, String hours, boolean isActive, 
						String street1, String street2, String city,
						String state, String zip, CuisineType cuisineType, 
						Companies company ) {
		this.restaurantId = restaurantId;
		this.name = name;
		this.description = description;
        this.menu = menu;
		this.hours = hours;
		this.isActive = isActive;
        this.street1= street1;
		this.street2 = street2;
		this.city  = city ;
        this.state = state;
		this.zip = zip;
		this.cuisineType = cuisineType;
        this.company = company;
	}

    // reading records from MySQL, where we only have the restaurantId,
    public Restaurants(int restaurantId) {
		this.restaurantId = restaurantId;
	}

    // creating new records, where the restaurantId may not be
	// assigned yet since it is auto-generated by MySQL.
    public Restaurants (String name, String description,
                        String menu, String hours, boolean isActive, 
                        String street1, String street2, String city,
                        String state, String zip, CuisineType cuisineType, 
                        Companies company ) {
    this.name = name;
    this.description = description;
    this.menu = menu;
    this.hours = hours;
    this.isActive = isActive;
    this.street1= street1;
    this.street2 = street2;
    this.city  = city ;
    this.state = state;
    this.zip = zip;
    this.cuisineType = cuisineType;
    this.company = company;
    }

	/** Getters and setters. */

    public int getrestaurantId() {
		return restaurantId;
	}

	public void setrestaurantId(int restaurantId) {
		this.restaurantId = restaurantId;
	}

    public String getname() {
		return name;
	}

	public void setname(String name) {
		this.name = name;
	}

    public String getdescription() {
		return description;
	}

	public void setdescription(String description) {
		this.description = description;
	}

    public String getmenu() {
		return menu;
	}

	public void setmenu(String menu) {
		this.menu = menu;
	}

    public String gethours() {
		return hours;
	}

	public void sethours(String hours) {
		this.hours = hours;
	}
    public boolean getisActive() {
		return isActive;
	}

	public void getisActive(boolean isActive) {
		this.isActive = isActive;
	}

    public String getstreet1() {
		return street1;
	}

	public void setstreet1(String street1) {
		this.street1 = street1;
	}

    public String getstreet2() {
		return street2;
	}

	public void setstreet2(String street2) {
		this.street2 = street2;
	}

    public String getcity() {
		return city;
	}

	public void setcity(String city) {
		this.city = city;
	}

    public String getstate() {
		return state;
	}

	public void setstate(String state) {
		this.state = state;
	}

    public String getzip() {
		return zip;
	}

	public void setzip(String zip) {
		this.zip = zip;
	}

    public CuisineType getCuisineType() {
		return cuisineType;
	}

	public void setCuisineType(CuisineType cuisineType) {
		this.cuisineType = cuisineType;
	}

    public Companies getcompany() {
		return company;
	}

	public void setcompany(Companies company) {
		this.company = company;
	}
}
